.class public Lcom/hack/agent/HackAppProvider;
.super Lcom/hack/agent/ProviderBase;
.source "HackAppProvider.java"


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lcom/hack/agent/HackAppProvider$P149;,
        Lcom/hack/agent/HackAppProvider$P148;,
        Lcom/hack/agent/HackAppProvider$P147;,
        Lcom/hack/agent/HackAppProvider$P146;,
        Lcom/hack/agent/HackAppProvider$P145;,
        Lcom/hack/agent/HackAppProvider$P144;,
        Lcom/hack/agent/HackAppProvider$P143;,
        Lcom/hack/agent/HackAppProvider$P142;,
        Lcom/hack/agent/HackAppProvider$P141;,
        Lcom/hack/agent/HackAppProvider$P140;,
        Lcom/hack/agent/HackAppProvider$P139;,
        Lcom/hack/agent/HackAppProvider$P138;,
        Lcom/hack/agent/HackAppProvider$P137;,
        Lcom/hack/agent/HackAppProvider$P136;,
        Lcom/hack/agent/HackAppProvider$P135;,
        Lcom/hack/agent/HackAppProvider$P134;,
        Lcom/hack/agent/HackAppProvider$P133;,
        Lcom/hack/agent/HackAppProvider$P132;,
        Lcom/hack/agent/HackAppProvider$P131;,
        Lcom/hack/agent/HackAppProvider$P130;,
        Lcom/hack/agent/HackAppProvider$P129;,
        Lcom/hack/agent/HackAppProvider$P128;,
        Lcom/hack/agent/HackAppProvider$P127;,
        Lcom/hack/agent/HackAppProvider$P126;,
        Lcom/hack/agent/HackAppProvider$P125;,
        Lcom/hack/agent/HackAppProvider$P124;,
        Lcom/hack/agent/HackAppProvider$P123;,
        Lcom/hack/agent/HackAppProvider$P122;,
        Lcom/hack/agent/HackAppProvider$P121;,
        Lcom/hack/agent/HackAppProvider$P120;,
        Lcom/hack/agent/HackAppProvider$P119;,
        Lcom/hack/agent/HackAppProvider$P118;,
        Lcom/hack/agent/HackAppProvider$P117;,
        Lcom/hack/agent/HackAppProvider$P116;,
        Lcom/hack/agent/HackAppProvider$P115;,
        Lcom/hack/agent/HackAppProvider$P114;,
        Lcom/hack/agent/HackAppProvider$P113;,
        Lcom/hack/agent/HackAppProvider$P112;,
        Lcom/hack/agent/HackAppProvider$P111;,
        Lcom/hack/agent/HackAppProvider$P110;,
        Lcom/hack/agent/HackAppProvider$P109;,
        Lcom/hack/agent/HackAppProvider$P108;,
        Lcom/hack/agent/HackAppProvider$P107;,
        Lcom/hack/agent/HackAppProvider$P106;,
        Lcom/hack/agent/HackAppProvider$P105;,
        Lcom/hack/agent/HackAppProvider$P104;,
        Lcom/hack/agent/HackAppProvider$P103;,
        Lcom/hack/agent/HackAppProvider$P102;,
        Lcom/hack/agent/HackAppProvider$P101;,
        Lcom/hack/agent/HackAppProvider$P100;,
        Lcom/hack/agent/HackAppProvider$P99;,
        Lcom/hack/agent/HackAppProvider$P98;,
        Lcom/hack/agent/HackAppProvider$P97;,
        Lcom/hack/agent/HackAppProvider$P96;,
        Lcom/hack/agent/HackAppProvider$P95;,
        Lcom/hack/agent/HackAppProvider$P94;,
        Lcom/hack/agent/HackAppProvider$P93;,
        Lcom/hack/agent/HackAppProvider$P92;,
        Lcom/hack/agent/HackAppProvider$P91;,
        Lcom/hack/agent/HackAppProvider$P90;,
        Lcom/hack/agent/HackAppProvider$P89;,
        Lcom/hack/agent/HackAppProvider$P88;,
        Lcom/hack/agent/HackAppProvider$P87;,
        Lcom/hack/agent/HackAppProvider$P86;,
        Lcom/hack/agent/HackAppProvider$P85;,
        Lcom/hack/agent/HackAppProvider$P84;,
        Lcom/hack/agent/HackAppProvider$P83;,
        Lcom/hack/agent/HackAppProvider$P82;,
        Lcom/hack/agent/HackAppProvider$P81;,
        Lcom/hack/agent/HackAppProvider$P80;,
        Lcom/hack/agent/HackAppProvider$P79;,
        Lcom/hack/agent/HackAppProvider$P78;,
        Lcom/hack/agent/HackAppProvider$P77;,
        Lcom/hack/agent/HackAppProvider$P76;,
        Lcom/hack/agent/HackAppProvider$P75;,
        Lcom/hack/agent/HackAppProvider$P74;,
        Lcom/hack/agent/HackAppProvider$P73;,
        Lcom/hack/agent/HackAppProvider$P72;,
        Lcom/hack/agent/HackAppProvider$P71;,
        Lcom/hack/agent/HackAppProvider$P70;,
        Lcom/hack/agent/HackAppProvider$P69;,
        Lcom/hack/agent/HackAppProvider$P68;,
        Lcom/hack/agent/HackAppProvider$P67;,
        Lcom/hack/agent/HackAppProvider$P66;,
        Lcom/hack/agent/HackAppProvider$P65;,
        Lcom/hack/agent/HackAppProvider$P64;,
        Lcom/hack/agent/HackAppProvider$P63;,
        Lcom/hack/agent/HackAppProvider$P62;,
        Lcom/hack/agent/HackAppProvider$P61;,
        Lcom/hack/agent/HackAppProvider$P60;,
        Lcom/hack/agent/HackAppProvider$P59;,
        Lcom/hack/agent/HackAppProvider$P58;,
        Lcom/hack/agent/HackAppProvider$P57;,
        Lcom/hack/agent/HackAppProvider$P56;,
        Lcom/hack/agent/HackAppProvider$P55;,
        Lcom/hack/agent/HackAppProvider$P54;,
        Lcom/hack/agent/HackAppProvider$P53;,
        Lcom/hack/agent/HackAppProvider$P52;,
        Lcom/hack/agent/HackAppProvider$P51;,
        Lcom/hack/agent/HackAppProvider$P50;,
        Lcom/hack/agent/HackAppProvider$P49;,
        Lcom/hack/agent/HackAppProvider$P48;,
        Lcom/hack/agent/HackAppProvider$P47;,
        Lcom/hack/agent/HackAppProvider$P46;,
        Lcom/hack/agent/HackAppProvider$P45;,
        Lcom/hack/agent/HackAppProvider$P44;,
        Lcom/hack/agent/HackAppProvider$P43;,
        Lcom/hack/agent/HackAppProvider$P42;,
        Lcom/hack/agent/HackAppProvider$P41;,
        Lcom/hack/agent/HackAppProvider$P40;,
        Lcom/hack/agent/HackAppProvider$P39;,
        Lcom/hack/agent/HackAppProvider$P38;,
        Lcom/hack/agent/HackAppProvider$P37;,
        Lcom/hack/agent/HackAppProvider$P36;,
        Lcom/hack/agent/HackAppProvider$P35;,
        Lcom/hack/agent/HackAppProvider$P34;,
        Lcom/hack/agent/HackAppProvider$P33;,
        Lcom/hack/agent/HackAppProvider$P32;,
        Lcom/hack/agent/HackAppProvider$P31;,
        Lcom/hack/agent/HackAppProvider$P30;,
        Lcom/hack/agent/HackAppProvider$P29;,
        Lcom/hack/agent/HackAppProvider$P28;,
        Lcom/hack/agent/HackAppProvider$P27;,
        Lcom/hack/agent/HackAppProvider$P26;,
        Lcom/hack/agent/HackAppProvider$P25;,
        Lcom/hack/agent/HackAppProvider$P24;,
        Lcom/hack/agent/HackAppProvider$P23;,
        Lcom/hack/agent/HackAppProvider$P22;,
        Lcom/hack/agent/HackAppProvider$P21;,
        Lcom/hack/agent/HackAppProvider$P20;,
        Lcom/hack/agent/HackAppProvider$P19;,
        Lcom/hack/agent/HackAppProvider$P18;,
        Lcom/hack/agent/HackAppProvider$P17;,
        Lcom/hack/agent/HackAppProvider$P16;,
        Lcom/hack/agent/HackAppProvider$P15;,
        Lcom/hack/agent/HackAppProvider$P14;,
        Lcom/hack/agent/HackAppProvider$P13;,
        Lcom/hack/agent/HackAppProvider$P12;,
        Lcom/hack/agent/HackAppProvider$P11;,
        Lcom/hack/agent/HackAppProvider$P10;,
        Lcom/hack/agent/HackAppProvider$P9;,
        Lcom/hack/agent/HackAppProvider$P8;,
        Lcom/hack/agent/HackAppProvider$P7;,
        Lcom/hack/agent/HackAppProvider$P6;,
        Lcom/hack/agent/HackAppProvider$P5;,
        Lcom/hack/agent/HackAppProvider$P4;,
        Lcom/hack/agent/HackAppProvider$P3;,
        Lcom/hack/agent/HackAppProvider$P2;,
        Lcom/hack/agent/HackAppProvider$P1;,
        Lcom/hack/agent/HackAppProvider$P0;
    }
.end annotation


# direct methods
.method public constructor <init>()V
    .locals 0

    .line 5
    invoke-direct {p0}, Lcom/hack/agent/ProviderBase;-><init>()V

    return-void
.end method


# virtual methods
.method public getProviderCallType()I
    .locals 1

    const/16 v0, 0x67

    return v0
.end method
